# LAAWS demo pywb config file
# ========================================

collections:
    all: $all

# Autoindexing of WARCs
autoindex: 30

# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: true

